name: Bump version

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Version type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - manual
      override:
        description: 'Manual version override'
        required: false
        type: string
        placeholder: 'x.x.x'

jobs:
  bump:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version
        run: |
          if [[ -z $VERSION_OVERRIDE ]]; then
            npm version $TYPE -m "Bump to version %s"
          else
            npm version $VERSION_OVERRIDE -m "Bump to version $VERSION_OVERRIDE"
          fi

      - name: Push to branch
        run: git push
